#############################################################################
# Makefile for building: ROBOTICA
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  guivigir/guivigir.pro
# Template: app
# Command: /opt/qt57/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile guivigir/guivigir.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -Iguivigir -I. -I/opt/qt57/include -I/opt/qt57/include/QtWidgets -I/opt/qt57/include/QtGui -I/opt/qt57/include/QtCore -I. -I. -I/opt/qt57/mkspecs/linux-g++
QMAKE         = /opt/qt57/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ROBOTICA1.0.0
DISTDIR = /home/yesser/labROS/guiqmake/.tmp/ROBOTICA1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qt57/lib
LIBS          = $(SUBLIBS) -L/opt/qt57/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = guivigir/main.cpp \
		guivigir/rosgui.cpp \
		guivigir/secondwindow.cpp \
		guivigir/thirdwindow.cpp \
		guivigir/fourth.cpp qrc_resources.cpp \
		moc_rosgui.cpp \
		moc_secondwindow.cpp \
		moc_thirdwindow.cpp \
		moc_fourth.cpp
OBJECTS       = main.o \
		rosgui.o \
		secondwindow.o \
		thirdwindow.o \
		fourth.o \
		qrc_resources.o \
		moc_rosgui.o \
		moc_secondwindow.o \
		moc_thirdwindow.o \
		moc_fourth.o
DIST          = /opt/qt57/mkspecs/features/spec_pre.prf \
		/opt/qt57/mkspecs/common/unix.conf \
		/opt/qt57/mkspecs/common/linux.conf \
		/opt/qt57/mkspecs/common/sanitize.conf \
		/opt/qt57/mkspecs/common/gcc-base.conf \
		/opt/qt57/mkspecs/common/gcc-base-unix.conf \
		/opt/qt57/mkspecs/common/g++-base.conf \
		/opt/qt57/mkspecs/common/g++-unix.conf \
		/opt/qt57/mkspecs/qconfig.pri \
		/opt/qt57/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt57/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_core.pri \
		/opt/qt57/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt57/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt57/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_network.pri \
		/opt/qt57/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt57/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt57/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt57/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt57/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt57/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt57/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt57/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt57/mkspecs/features/qt_functions.prf \
		/opt/qt57/mkspecs/features/qt_config.prf \
		/opt/qt57/mkspecs/linux-g++/qmake.conf \
		/opt/qt57/mkspecs/features/spec_post.prf \
		/opt/qt57/mkspecs/features/exclusive_builds.prf \
		/opt/qt57/mkspecs/features/toolchain.prf \
		/opt/qt57/mkspecs/features/default_pre.prf \
		/opt/qt57/mkspecs/features/resolve_config.prf \
		/opt/qt57/mkspecs/features/default_post.prf \
		/opt/qt57/mkspecs/features/qml_debug.prf \
		/opt/qt57/mkspecs/features/warn_on.prf \
		/opt/qt57/mkspecs/features/qt.prf \
		/opt/qt57/mkspecs/features/resources.prf \
		/opt/qt57/mkspecs/features/moc.prf \
		/opt/qt57/mkspecs/features/unix/opengl.prf \
		/opt/qt57/mkspecs/features/uic.prf \
		/opt/qt57/mkspecs/features/unix/thread.prf \
		/opt/qt57/mkspecs/features/file_copies.prf \
		/opt/qt57/mkspecs/features/testcase_targets.prf \
		/opt/qt57/mkspecs/features/exceptions.prf \
		/opt/qt57/mkspecs/features/yacc.prf \
		/opt/qt57/mkspecs/features/lex.prf \
		guivigir/guivigir/guivigir.pro guivigir/rosgui.h \
		guivigir/secondwindow.h \
		guivigir/thirdwindow.h \
		guivigir/fourth.h guivigir/main.cpp \
		guivigir/rosgui.cpp \
		guivigir/secondwindow.cpp \
		guivigir/thirdwindow.cpp \
		guivigir/fourth.cpp
QMAKE_TARGET  = ROBOTICA
DESTDIR       = 
TARGET        = ROBOTICA


first: all
####### Build rules

$(TARGET): ui_rosgui.h ui_secondwindow.h ui_thirdwindow.h ui_fourth.h ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: guivigir/guivigir.pro /opt/qt57/mkspecs/linux-g++/qmake.conf /opt/qt57/mkspecs/features/spec_pre.prf \
		/opt/qt57/mkspecs/common/unix.conf \
		/opt/qt57/mkspecs/common/linux.conf \
		/opt/qt57/mkspecs/common/sanitize.conf \
		/opt/qt57/mkspecs/common/gcc-base.conf \
		/opt/qt57/mkspecs/common/gcc-base-unix.conf \
		/opt/qt57/mkspecs/common/g++-base.conf \
		/opt/qt57/mkspecs/common/g++-unix.conf \
		/opt/qt57/mkspecs/qconfig.pri \
		/opt/qt57/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt57/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_core.pri \
		/opt/qt57/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt57/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt57/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_network.pri \
		/opt/qt57/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt57/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt57/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt57/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt57/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt57/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt57/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt57/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt57/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt57/mkspecs/features/qt_functions.prf \
		/opt/qt57/mkspecs/features/qt_config.prf \
		/opt/qt57/mkspecs/linux-g++/qmake.conf \
		/opt/qt57/mkspecs/features/spec_post.prf \
		/opt/qt57/mkspecs/features/exclusive_builds.prf \
		/opt/qt57/mkspecs/features/toolchain.prf \
		/opt/qt57/mkspecs/features/default_pre.prf \
		/opt/qt57/mkspecs/features/resolve_config.prf \
		/opt/qt57/mkspecs/features/default_post.prf \
		/opt/qt57/mkspecs/features/qml_debug.prf \
		/opt/qt57/mkspecs/features/warn_on.prf \
		/opt/qt57/mkspecs/features/qt.prf \
		/opt/qt57/mkspecs/features/resources.prf \
		/opt/qt57/mkspecs/features/moc.prf \
		/opt/qt57/mkspecs/features/unix/opengl.prf \
		/opt/qt57/mkspecs/features/uic.prf \
		/opt/qt57/mkspecs/features/unix/thread.prf \
		/opt/qt57/mkspecs/features/file_copies.prf \
		/opt/qt57/mkspecs/features/testcase_targets.prf \
		/opt/qt57/mkspecs/features/exceptions.prf \
		/opt/qt57/mkspecs/features/yacc.prf \
		/opt/qt57/mkspecs/features/lex.prf \
		guivigir/guivigir.pro \
		guivigir/resources.qrc \
		/opt/qt57/lib/libQt5Widgets.prl \
		/opt/qt57/lib/libQt5Gui.prl \
		/opt/qt57/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile guivigir/guivigir.pro
/opt/qt57/mkspecs/features/spec_pre.prf:
/opt/qt57/mkspecs/common/unix.conf:
/opt/qt57/mkspecs/common/linux.conf:
/opt/qt57/mkspecs/common/sanitize.conf:
/opt/qt57/mkspecs/common/gcc-base.conf:
/opt/qt57/mkspecs/common/gcc-base-unix.conf:
/opt/qt57/mkspecs/common/g++-base.conf:
/opt/qt57/mkspecs/common/g++-unix.conf:
/opt/qt57/mkspecs/qconfig.pri:
/opt/qt57/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt57/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt57/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt57/mkspecs/modules/qt_lib_core.pri:
/opt/qt57/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt57/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt57/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt57/mkspecs/modules/qt_lib_gui.pri:
/opt/qt57/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt57/mkspecs/modules/qt_lib_network.pri:
/opt/qt57/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt57/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt57/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt57/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt57/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt57/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qt57/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt57/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt57/mkspecs/modules/qt_lib_sql.pri:
/opt/qt57/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt57/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt57/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt57/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt57/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt57/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt57/mkspecs/modules/qt_lib_xml.pri:
/opt/qt57/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt57/mkspecs/features/qt_functions.prf:
/opt/qt57/mkspecs/features/qt_config.prf:
/opt/qt57/mkspecs/linux-g++/qmake.conf:
/opt/qt57/mkspecs/features/spec_post.prf:
/opt/qt57/mkspecs/features/exclusive_builds.prf:
/opt/qt57/mkspecs/features/toolchain.prf:
/opt/qt57/mkspecs/features/default_pre.prf:
/opt/qt57/mkspecs/features/resolve_config.prf:
/opt/qt57/mkspecs/features/default_post.prf:
/opt/qt57/mkspecs/features/qml_debug.prf:
/opt/qt57/mkspecs/features/warn_on.prf:
/opt/qt57/mkspecs/features/qt.prf:
/opt/qt57/mkspecs/features/resources.prf:
/opt/qt57/mkspecs/features/moc.prf:
/opt/qt57/mkspecs/features/unix/opengl.prf:
/opt/qt57/mkspecs/features/uic.prf:
/opt/qt57/mkspecs/features/unix/thread.prf:
/opt/qt57/mkspecs/features/file_copies.prf:
/opt/qt57/mkspecs/features/testcase_targets.prf:
/opt/qt57/mkspecs/features/exceptions.prf:
/opt/qt57/mkspecs/features/yacc.prf:
/opt/qt57/mkspecs/features/lex.prf:
guivigir/guivigir.pro:
guivigir/resources.qrc:
/opt/qt57/lib/libQt5Widgets.prl:
/opt/qt57/lib/libQt5Gui.prl:
/opt/qt57/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile guivigir/guivigir.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents guivigir/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents guivigir/rosgui.h guivigir/secondwindow.h guivigir/thirdwindow.h guivigir/fourth.h $(DISTDIR)/
	$(COPY_FILE) --parents guivigir/main.cpp guivigir/rosgui.cpp guivigir/secondwindow.cpp guivigir/thirdwindow.cpp guivigir/fourth.cpp $(DISTDIR)/
	$(COPY_FILE) --parents guivigir/rosgui.ui guivigir/secondwindow.ui guivigir/thirdwindow.ui guivigir/fourth.ui guivigir/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: guivigir/resources.qrc \
		/opt/qt57/bin/rcc \
		guivigir/img/AS.png \
		guivigir/img/ROS_INDUSTRIAL.jpg \
		guivigir/img/Yaskawa_Motoman_Logo.png \
		guivigir/img/noun_.png \
		guivigir/img/ABB.png \
		guivigir/img/ROS_INDUSTRIAL.png \
		guivigir/img/CD.png \
		guivigir/img/noun_1036029_cc.png \
		guivigir/img/dhparameter.png \
		guivigir/img/CI.png \
		guivigir/img/noun_1036042_cc.png \
		guivigir/img/Uni.jpg \
		guivigir/img/noun_319786_cc.png \
		guivigir/img/ros.jpg \
		guivigir/img/noun_1450480_cc.png \
		guivigir/img/ros.png \
		guivigir/img/1448635827949.png
	/opt/qt57/bin/rcc -name resources guivigir/resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_rosgui.cpp moc_secondwindow.cpp moc_thirdwindow.cpp moc_fourth.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_rosgui.cpp moc_secondwindow.cpp moc_thirdwindow.cpp moc_fourth.cpp
moc_rosgui.cpp: /opt/qt57/include/QtWidgets/QMainWindow \
		/opt/qt57/include/QtWidgets/qmainwindow.h \
		/opt/qt57/include/QtWidgets/qwidget.h \
		/opt/qt57/include/QtGui/qwindowdefs.h \
		/opt/qt57/include/QtCore/qglobal.h \
		/opt/qt57/include/QtCore/qconfig.h \
		/opt/qt57/include/QtCore/qfeatures.h \
		/opt/qt57/include/QtCore/qsystemdetection.h \
		/opt/qt57/include/QtCore/qprocessordetection.h \
		/opt/qt57/include/QtCore/qcompilerdetection.h \
		/opt/qt57/include/QtCore/qtypeinfo.h \
		/opt/qt57/include/QtCore/qtypetraits.h \
		/opt/qt57/include/QtCore/qisenum.h \
		/opt/qt57/include/QtCore/qsysinfo.h \
		/opt/qt57/include/QtCore/qlogging.h \
		/opt/qt57/include/QtCore/qflags.h \
		/opt/qt57/include/QtCore/qatomic.h \
		/opt/qt57/include/QtCore/qbasicatomic.h \
		/opt/qt57/include/QtCore/qatomic_bootstrap.h \
		/opt/qt57/include/QtCore/qgenericatomic.h \
		/opt/qt57/include/QtCore/qatomic_cxx11.h \
		/opt/qt57/include/QtCore/qatomic_msvc.h \
		/opt/qt57/include/QtCore/qglobalstatic.h \
		/opt/qt57/include/QtCore/qmutex.h \
		/opt/qt57/include/QtCore/qnumeric.h \
		/opt/qt57/include/QtCore/qversiontagging.h \
		/opt/qt57/include/QtCore/qobjectdefs.h \
		/opt/qt57/include/QtCore/qnamespace.h \
		/opt/qt57/include/QtCore/qobjectdefs_impl.h \
		/opt/qt57/include/QtGui/qwindowdefs_win.h \
		/opt/qt57/include/QtCore/qobject.h \
		/opt/qt57/include/QtCore/qstring.h \
		/opt/qt57/include/QtCore/qchar.h \
		/opt/qt57/include/QtCore/qbytearray.h \
		/opt/qt57/include/QtCore/qrefcount.h \
		/opt/qt57/include/QtCore/qarraydata.h \
		/opt/qt57/include/QtCore/qstringbuilder.h \
		/opt/qt57/include/QtCore/qlist.h \
		/opt/qt57/include/QtCore/qalgorithms.h \
		/opt/qt57/include/QtCore/qiterator.h \
		/opt/qt57/include/QtCore/qhashfunctions.h \
		/opt/qt57/include/QtCore/qpair.h \
		/opt/qt57/include/QtCore/qbytearraylist.h \
		/opt/qt57/include/QtCore/qstringlist.h \
		/opt/qt57/include/QtCore/qregexp.h \
		/opt/qt57/include/QtCore/qstringmatcher.h \
		/opt/qt57/include/QtCore/qcoreevent.h \
		/opt/qt57/include/QtCore/qscopedpointer.h \
		/opt/qt57/include/QtCore/qmetatype.h \
		/opt/qt57/include/QtCore/qvarlengtharray.h \
		/opt/qt57/include/QtCore/qcontainerfwd.h \
		/opt/qt57/include/QtCore/qobject_impl.h \
		/opt/qt57/include/QtCore/qmargins.h \
		/opt/qt57/include/QtGui/qpaintdevice.h \
		/opt/qt57/include/QtCore/qrect.h \
		/opt/qt57/include/QtCore/qsize.h \
		/opt/qt57/include/QtCore/qpoint.h \
		/opt/qt57/include/QtGui/qpalette.h \
		/opt/qt57/include/QtGui/qcolor.h \
		/opt/qt57/include/QtGui/qrgb.h \
		/opt/qt57/include/QtGui/qrgba64.h \
		/opt/qt57/include/QtGui/qbrush.h \
		/opt/qt57/include/QtCore/qvector.h \
		/opt/qt57/include/QtGui/qmatrix.h \
		/opt/qt57/include/QtGui/qpolygon.h \
		/opt/qt57/include/QtGui/qregion.h \
		/opt/qt57/include/QtCore/qdatastream.h \
		/opt/qt57/include/QtCore/qiodevice.h \
		/opt/qt57/include/QtCore/qline.h \
		/opt/qt57/include/QtGui/qtransform.h \
		/opt/qt57/include/QtGui/qpainterpath.h \
		/opt/qt57/include/QtGui/qimage.h \
		/opt/qt57/include/QtGui/qpixelformat.h \
		/opt/qt57/include/QtGui/qpixmap.h \
		/opt/qt57/include/QtCore/qsharedpointer.h \
		/opt/qt57/include/QtCore/qshareddata.h \
		/opt/qt57/include/QtCore/qhash.h \
		/opt/qt57/include/QtCore/qsharedpointer_impl.h \
		/opt/qt57/include/QtGui/qfont.h \
		/opt/qt57/include/QtGui/qfontmetrics.h \
		/opt/qt57/include/QtGui/qfontinfo.h \
		/opt/qt57/include/QtWidgets/qsizepolicy.h \
		/opt/qt57/include/QtGui/qcursor.h \
		/opt/qt57/include/QtGui/qkeysequence.h \
		/opt/qt57/include/QtGui/qevent.h \
		/opt/qt57/include/QtCore/qvariant.h \
		/opt/qt57/include/QtCore/qmap.h \
		/opt/qt57/include/QtCore/qdebug.h \
		/opt/qt57/include/QtCore/qtextstream.h \
		/opt/qt57/include/QtCore/qlocale.h \
		/opt/qt57/include/QtCore/qset.h \
		/opt/qt57/include/QtCore/qcontiguouscache.h \
		/opt/qt57/include/QtCore/qurl.h \
		/opt/qt57/include/QtCore/qurlquery.h \
		/opt/qt57/include/QtCore/qfile.h \
		/opt/qt57/include/QtCore/qfiledevice.h \
		/opt/qt57/include/QtGui/qvector2d.h \
		/opt/qt57/include/QtGui/qtouchdevice.h \
		/opt/qt57/include/QtWidgets/qtabwidget.h \
		/opt/qt57/include/QtGui/qicon.h \
		guivigir/secondwindow.h \
		guivigir/thirdwindow.h \
		guivigir/fourth.h \
		guivigir/rosgui.h \
		/opt/qt57/bin/moc
	/opt/qt57/bin/moc $(DEFINES) -I/opt/qt57/mkspecs/linux-g++ -I/home/yesser/labROS/guiqmake/guivigir -I/opt/qt57/include -I/opt/qt57/include/QtWidgets -I/opt/qt57/include/QtGui -I/opt/qt57/include/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include guivigir/rosgui.h -o moc_rosgui.cpp

moc_secondwindow.cpp: /opt/qt57/include/QtWidgets/QMainWindow \
		/opt/qt57/include/QtWidgets/qmainwindow.h \
		/opt/qt57/include/QtWidgets/qwidget.h \
		/opt/qt57/include/QtGui/qwindowdefs.h \
		/opt/qt57/include/QtCore/qglobal.h \
		/opt/qt57/include/QtCore/qconfig.h \
		/opt/qt57/include/QtCore/qfeatures.h \
		/opt/qt57/include/QtCore/qsystemdetection.h \
		/opt/qt57/include/QtCore/qprocessordetection.h \
		/opt/qt57/include/QtCore/qcompilerdetection.h \
		/opt/qt57/include/QtCore/qtypeinfo.h \
		/opt/qt57/include/QtCore/qtypetraits.h \
		/opt/qt57/include/QtCore/qisenum.h \
		/opt/qt57/include/QtCore/qsysinfo.h \
		/opt/qt57/include/QtCore/qlogging.h \
		/opt/qt57/include/QtCore/qflags.h \
		/opt/qt57/include/QtCore/qatomic.h \
		/opt/qt57/include/QtCore/qbasicatomic.h \
		/opt/qt57/include/QtCore/qatomic_bootstrap.h \
		/opt/qt57/include/QtCore/qgenericatomic.h \
		/opt/qt57/include/QtCore/qatomic_cxx11.h \
		/opt/qt57/include/QtCore/qatomic_msvc.h \
		/opt/qt57/include/QtCore/qglobalstatic.h \
		/opt/qt57/include/QtCore/qmutex.h \
		/opt/qt57/include/QtCore/qnumeric.h \
		/opt/qt57/include/QtCore/qversiontagging.h \
		/opt/qt57/include/QtCore/qobjectdefs.h \
		/opt/qt57/include/QtCore/qnamespace.h \
		/opt/qt57/include/QtCore/qobjectdefs_impl.h \
		/opt/qt57/include/QtGui/qwindowdefs_win.h \
		/opt/qt57/include/QtCore/qobject.h \
		/opt/qt57/include/QtCore/qstring.h \
		/opt/qt57/include/QtCore/qchar.h \
		/opt/qt57/include/QtCore/qbytearray.h \
		/opt/qt57/include/QtCore/qrefcount.h \
		/opt/qt57/include/QtCore/qarraydata.h \
		/opt/qt57/include/QtCore/qstringbuilder.h \
		/opt/qt57/include/QtCore/qlist.h \
		/opt/qt57/include/QtCore/qalgorithms.h \
		/opt/qt57/include/QtCore/qiterator.h \
		/opt/qt57/include/QtCore/qhashfunctions.h \
		/opt/qt57/include/QtCore/qpair.h \
		/opt/qt57/include/QtCore/qbytearraylist.h \
		/opt/qt57/include/QtCore/qstringlist.h \
		/opt/qt57/include/QtCore/qregexp.h \
		/opt/qt57/include/QtCore/qstringmatcher.h \
		/opt/qt57/include/QtCore/qcoreevent.h \
		/opt/qt57/include/QtCore/qscopedpointer.h \
		/opt/qt57/include/QtCore/qmetatype.h \
		/opt/qt57/include/QtCore/qvarlengtharray.h \
		/opt/qt57/include/QtCore/qcontainerfwd.h \
		/opt/qt57/include/QtCore/qobject_impl.h \
		/opt/qt57/include/QtCore/qmargins.h \
		/opt/qt57/include/QtGui/qpaintdevice.h \
		/opt/qt57/include/QtCore/qrect.h \
		/opt/qt57/include/QtCore/qsize.h \
		/opt/qt57/include/QtCore/qpoint.h \
		/opt/qt57/include/QtGui/qpalette.h \
		/opt/qt57/include/QtGui/qcolor.h \
		/opt/qt57/include/QtGui/qrgb.h \
		/opt/qt57/include/QtGui/qrgba64.h \
		/opt/qt57/include/QtGui/qbrush.h \
		/opt/qt57/include/QtCore/qvector.h \
		/opt/qt57/include/QtGui/qmatrix.h \
		/opt/qt57/include/QtGui/qpolygon.h \
		/opt/qt57/include/QtGui/qregion.h \
		/opt/qt57/include/QtCore/qdatastream.h \
		/opt/qt57/include/QtCore/qiodevice.h \
		/opt/qt57/include/QtCore/qline.h \
		/opt/qt57/include/QtGui/qtransform.h \
		/opt/qt57/include/QtGui/qpainterpath.h \
		/opt/qt57/include/QtGui/qimage.h \
		/opt/qt57/include/QtGui/qpixelformat.h \
		/opt/qt57/include/QtGui/qpixmap.h \
		/opt/qt57/include/QtCore/qsharedpointer.h \
		/opt/qt57/include/QtCore/qshareddata.h \
		/opt/qt57/include/QtCore/qhash.h \
		/opt/qt57/include/QtCore/qsharedpointer_impl.h \
		/opt/qt57/include/QtGui/qfont.h \
		/opt/qt57/include/QtGui/qfontmetrics.h \
		/opt/qt57/include/QtGui/qfontinfo.h \
		/opt/qt57/include/QtWidgets/qsizepolicy.h \
		/opt/qt57/include/QtGui/qcursor.h \
		/opt/qt57/include/QtGui/qkeysequence.h \
		/opt/qt57/include/QtGui/qevent.h \
		/opt/qt57/include/QtCore/qvariant.h \
		/opt/qt57/include/QtCore/qmap.h \
		/opt/qt57/include/QtCore/qdebug.h \
		/opt/qt57/include/QtCore/qtextstream.h \
		/opt/qt57/include/QtCore/qlocale.h \
		/opt/qt57/include/QtCore/qset.h \
		/opt/qt57/include/QtCore/qcontiguouscache.h \
		/opt/qt57/include/QtCore/qurl.h \
		/opt/qt57/include/QtCore/qurlquery.h \
		/opt/qt57/include/QtCore/qfile.h \
		/opt/qt57/include/QtCore/qfiledevice.h \
		/opt/qt57/include/QtGui/qvector2d.h \
		/opt/qt57/include/QtGui/qtouchdevice.h \
		/opt/qt57/include/QtWidgets/qtabwidget.h \
		/opt/qt57/include/QtGui/qicon.h \
		guivigir/secondwindow.h \
		/opt/qt57/bin/moc
	/opt/qt57/bin/moc $(DEFINES) -I/opt/qt57/mkspecs/linux-g++ -I/home/yesser/labROS/guiqmake/guivigir -I/opt/qt57/include -I/opt/qt57/include/QtWidgets -I/opt/qt57/include/QtGui -I/opt/qt57/include/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include guivigir/secondwindow.h -o moc_secondwindow.cpp

moc_thirdwindow.cpp: /opt/qt57/include/QtWidgets/QMainWindow \
		/opt/qt57/include/QtWidgets/qmainwindow.h \
		/opt/qt57/include/QtWidgets/qwidget.h \
		/opt/qt57/include/QtGui/qwindowdefs.h \
		/opt/qt57/include/QtCore/qglobal.h \
		/opt/qt57/include/QtCore/qconfig.h \
		/opt/qt57/include/QtCore/qfeatures.h \
		/opt/qt57/include/QtCore/qsystemdetection.h \
		/opt/qt57/include/QtCore/qprocessordetection.h \
		/opt/qt57/include/QtCore/qcompilerdetection.h \
		/opt/qt57/include/QtCore/qtypeinfo.h \
		/opt/qt57/include/QtCore/qtypetraits.h \
		/opt/qt57/include/QtCore/qisenum.h \
		/opt/qt57/include/QtCore/qsysinfo.h \
		/opt/qt57/include/QtCore/qlogging.h \
		/opt/qt57/include/QtCore/qflags.h \
		/opt/qt57/include/QtCore/qatomic.h \
		/opt/qt57/include/QtCore/qbasicatomic.h \
		/opt/qt57/include/QtCore/qatomic_bootstrap.h \
		/opt/qt57/include/QtCore/qgenericatomic.h \
		/opt/qt57/include/QtCore/qatomic_cxx11.h \
		/opt/qt57/include/QtCore/qatomic_msvc.h \
		/opt/qt57/include/QtCore/qglobalstatic.h \
		/opt/qt57/include/QtCore/qmutex.h \
		/opt/qt57/include/QtCore/qnumeric.h \
		/opt/qt57/include/QtCore/qversiontagging.h \
		/opt/qt57/include/QtCore/qobjectdefs.h \
		/opt/qt57/include/QtCore/qnamespace.h \
		/opt/qt57/include/QtCore/qobjectdefs_impl.h \
		/opt/qt57/include/QtGui/qwindowdefs_win.h \
		/opt/qt57/include/QtCore/qobject.h \
		/opt/qt57/include/QtCore/qstring.h \
		/opt/qt57/include/QtCore/qchar.h \
		/opt/qt57/include/QtCore/qbytearray.h \
		/opt/qt57/include/QtCore/qrefcount.h \
		/opt/qt57/include/QtCore/qarraydata.h \
		/opt/qt57/include/QtCore/qstringbuilder.h \
		/opt/qt57/include/QtCore/qlist.h \
		/opt/qt57/include/QtCore/qalgorithms.h \
		/opt/qt57/include/QtCore/qiterator.h \
		/opt/qt57/include/QtCore/qhashfunctions.h \
		/opt/qt57/include/QtCore/qpair.h \
		/opt/qt57/include/QtCore/qbytearraylist.h \
		/opt/qt57/include/QtCore/qstringlist.h \
		/opt/qt57/include/QtCore/qregexp.h \
		/opt/qt57/include/QtCore/qstringmatcher.h \
		/opt/qt57/include/QtCore/qcoreevent.h \
		/opt/qt57/include/QtCore/qscopedpointer.h \
		/opt/qt57/include/QtCore/qmetatype.h \
		/opt/qt57/include/QtCore/qvarlengtharray.h \
		/opt/qt57/include/QtCore/qcontainerfwd.h \
		/opt/qt57/include/QtCore/qobject_impl.h \
		/opt/qt57/include/QtCore/qmargins.h \
		/opt/qt57/include/QtGui/qpaintdevice.h \
		/opt/qt57/include/QtCore/qrect.h \
		/opt/qt57/include/QtCore/qsize.h \
		/opt/qt57/include/QtCore/qpoint.h \
		/opt/qt57/include/QtGui/qpalette.h \
		/opt/qt57/include/QtGui/qcolor.h \
		/opt/qt57/include/QtGui/qrgb.h \
		/opt/qt57/include/QtGui/qrgba64.h \
		/opt/qt57/include/QtGui/qbrush.h \
		/opt/qt57/include/QtCore/qvector.h \
		/opt/qt57/include/QtGui/qmatrix.h \
		/opt/qt57/include/QtGui/qpolygon.h \
		/opt/qt57/include/QtGui/qregion.h \
		/opt/qt57/include/QtCore/qdatastream.h \
		/opt/qt57/include/QtCore/qiodevice.h \
		/opt/qt57/include/QtCore/qline.h \
		/opt/qt57/include/QtGui/qtransform.h \
		/opt/qt57/include/QtGui/qpainterpath.h \
		/opt/qt57/include/QtGui/qimage.h \
		/opt/qt57/include/QtGui/qpixelformat.h \
		/opt/qt57/include/QtGui/qpixmap.h \
		/opt/qt57/include/QtCore/qsharedpointer.h \
		/opt/qt57/include/QtCore/qshareddata.h \
		/opt/qt57/include/QtCore/qhash.h \
		/opt/qt57/include/QtCore/qsharedpointer_impl.h \
		/opt/qt57/include/QtGui/qfont.h \
		/opt/qt57/include/QtGui/qfontmetrics.h \
		/opt/qt57/include/QtGui/qfontinfo.h \
		/opt/qt57/include/QtWidgets/qsizepolicy.h \
		/opt/qt57/include/QtGui/qcursor.h \
		/opt/qt57/include/QtGui/qkeysequence.h \
		/opt/qt57/include/QtGui/qevent.h \
		/opt/qt57/include/QtCore/qvariant.h \
		/opt/qt57/include/QtCore/qmap.h \
		/opt/qt57/include/QtCore/qdebug.h \
		/opt/qt57/include/QtCore/qtextstream.h \
		/opt/qt57/include/QtCore/qlocale.h \
		/opt/qt57/include/QtCore/qset.h \
		/opt/qt57/include/QtCore/qcontiguouscache.h \
		/opt/qt57/include/QtCore/qurl.h \
		/opt/qt57/include/QtCore/qurlquery.h \
		/opt/qt57/include/QtCore/qfile.h \
		/opt/qt57/include/QtCore/qfiledevice.h \
		/opt/qt57/include/QtGui/qvector2d.h \
		/opt/qt57/include/QtGui/qtouchdevice.h \
		/opt/qt57/include/QtWidgets/qtabwidget.h \
		/opt/qt57/include/QtGui/qicon.h \
		guivigir/thirdwindow.h \
		/opt/qt57/bin/moc
	/opt/qt57/bin/moc $(DEFINES) -I/opt/qt57/mkspecs/linux-g++ -I/home/yesser/labROS/guiqmake/guivigir -I/opt/qt57/include -I/opt/qt57/include/QtWidgets -I/opt/qt57/include/QtGui -I/opt/qt57/include/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include guivigir/thirdwindow.h -o moc_thirdwindow.cpp

moc_fourth.cpp: /opt/qt57/include/QtWidgets/QMainWindow \
		/opt/qt57/include/QtWidgets/qmainwindow.h \
		/opt/qt57/include/QtWidgets/qwidget.h \
		/opt/qt57/include/QtGui/qwindowdefs.h \
		/opt/qt57/include/QtCore/qglobal.h \
		/opt/qt57/include/QtCore/qconfig.h \
		/opt/qt57/include/QtCore/qfeatures.h \
		/opt/qt57/include/QtCore/qsystemdetection.h \
		/opt/qt57/include/QtCore/qprocessordetection.h \
		/opt/qt57/include/QtCore/qcompilerdetection.h \
		/opt/qt57/include/QtCore/qtypeinfo.h \
		/opt/qt57/include/QtCore/qtypetraits.h \
		/opt/qt57/include/QtCore/qisenum.h \
		/opt/qt57/include/QtCore/qsysinfo.h \
		/opt/qt57/include/QtCore/qlogging.h \
		/opt/qt57/include/QtCore/qflags.h \
		/opt/qt57/include/QtCore/qatomic.h \
		/opt/qt57/include/QtCore/qbasicatomic.h \
		/opt/qt57/include/QtCore/qatomic_bootstrap.h \
		/opt/qt57/include/QtCore/qgenericatomic.h \
		/opt/qt57/include/QtCore/qatomic_cxx11.h \
		/opt/qt57/include/QtCore/qatomic_msvc.h \
		/opt/qt57/include/QtCore/qglobalstatic.h \
		/opt/qt57/include/QtCore/qmutex.h \
		/opt/qt57/include/QtCore/qnumeric.h \
		/opt/qt57/include/QtCore/qversiontagging.h \
		/opt/qt57/include/QtCore/qobjectdefs.h \
		/opt/qt57/include/QtCore/qnamespace.h \
		/opt/qt57/include/QtCore/qobjectdefs_impl.h \
		/opt/qt57/include/QtGui/qwindowdefs_win.h \
		/opt/qt57/include/QtCore/qobject.h \
		/opt/qt57/include/QtCore/qstring.h \
		/opt/qt57/include/QtCore/qchar.h \
		/opt/qt57/include/QtCore/qbytearray.h \
		/opt/qt57/include/QtCore/qrefcount.h \
		/opt/qt57/include/QtCore/qarraydata.h \
		/opt/qt57/include/QtCore/qstringbuilder.h \
		/opt/qt57/include/QtCore/qlist.h \
		/opt/qt57/include/QtCore/qalgorithms.h \
		/opt/qt57/include/QtCore/qiterator.h \
		/opt/qt57/include/QtCore/qhashfunctions.h \
		/opt/qt57/include/QtCore/qpair.h \
		/opt/qt57/include/QtCore/qbytearraylist.h \
		/opt/qt57/include/QtCore/qstringlist.h \
		/opt/qt57/include/QtCore/qregexp.h \
		/opt/qt57/include/QtCore/qstringmatcher.h \
		/opt/qt57/include/QtCore/qcoreevent.h \
		/opt/qt57/include/QtCore/qscopedpointer.h \
		/opt/qt57/include/QtCore/qmetatype.h \
		/opt/qt57/include/QtCore/qvarlengtharray.h \
		/opt/qt57/include/QtCore/qcontainerfwd.h \
		/opt/qt57/include/QtCore/qobject_impl.h \
		/opt/qt57/include/QtCore/qmargins.h \
		/opt/qt57/include/QtGui/qpaintdevice.h \
		/opt/qt57/include/QtCore/qrect.h \
		/opt/qt57/include/QtCore/qsize.h \
		/opt/qt57/include/QtCore/qpoint.h \
		/opt/qt57/include/QtGui/qpalette.h \
		/opt/qt57/include/QtGui/qcolor.h \
		/opt/qt57/include/QtGui/qrgb.h \
		/opt/qt57/include/QtGui/qrgba64.h \
		/opt/qt57/include/QtGui/qbrush.h \
		/opt/qt57/include/QtCore/qvector.h \
		/opt/qt57/include/QtGui/qmatrix.h \
		/opt/qt57/include/QtGui/qpolygon.h \
		/opt/qt57/include/QtGui/qregion.h \
		/opt/qt57/include/QtCore/qdatastream.h \
		/opt/qt57/include/QtCore/qiodevice.h \
		/opt/qt57/include/QtCore/qline.h \
		/opt/qt57/include/QtGui/qtransform.h \
		/opt/qt57/include/QtGui/qpainterpath.h \
		/opt/qt57/include/QtGui/qimage.h \
		/opt/qt57/include/QtGui/qpixelformat.h \
		/opt/qt57/include/QtGui/qpixmap.h \
		/opt/qt57/include/QtCore/qsharedpointer.h \
		/opt/qt57/include/QtCore/qshareddata.h \
		/opt/qt57/include/QtCore/qhash.h \
		/opt/qt57/include/QtCore/qsharedpointer_impl.h \
		/opt/qt57/include/QtGui/qfont.h \
		/opt/qt57/include/QtGui/qfontmetrics.h \
		/opt/qt57/include/QtGui/qfontinfo.h \
		/opt/qt57/include/QtWidgets/qsizepolicy.h \
		/opt/qt57/include/QtGui/qcursor.h \
		/opt/qt57/include/QtGui/qkeysequence.h \
		/opt/qt57/include/QtGui/qevent.h \
		/opt/qt57/include/QtCore/qvariant.h \
		/opt/qt57/include/QtCore/qmap.h \
		/opt/qt57/include/QtCore/qdebug.h \
		/opt/qt57/include/QtCore/qtextstream.h \
		/opt/qt57/include/QtCore/qlocale.h \
		/opt/qt57/include/QtCore/qset.h \
		/opt/qt57/include/QtCore/qcontiguouscache.h \
		/opt/qt57/include/QtCore/qurl.h \
		/opt/qt57/include/QtCore/qurlquery.h \
		/opt/qt57/include/QtCore/qfile.h \
		/opt/qt57/include/QtCore/qfiledevice.h \
		/opt/qt57/include/QtGui/qvector2d.h \
		/opt/qt57/include/QtGui/qtouchdevice.h \
		/opt/qt57/include/QtWidgets/qtabwidget.h \
		/opt/qt57/include/QtGui/qicon.h \
		guivigir/fourth.h \
		/opt/qt57/bin/moc
	/opt/qt57/bin/moc $(DEFINES) -I/opt/qt57/mkspecs/linux-g++ -I/home/yesser/labROS/guiqmake/guivigir -I/opt/qt57/include -I/opt/qt57/include/QtWidgets -I/opt/qt57/include/QtGui -I/opt/qt57/include/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include guivigir/fourth.h -o moc_fourth.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_rosgui.h ui_secondwindow.h ui_thirdwindow.h ui_fourth.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_rosgui.h ui_secondwindow.h ui_thirdwindow.h ui_fourth.h ui_mainwindow.h
ui_rosgui.h: guivigir/rosgui.ui \
		/opt/qt57/bin/uic
	/opt/qt57/bin/uic guivigir/rosgui.ui -o ui_rosgui.h

ui_secondwindow.h: guivigir/secondwindow.ui \
		/opt/qt57/bin/uic
	/opt/qt57/bin/uic guivigir/secondwindow.ui -o ui_secondwindow.h

ui_thirdwindow.h: guivigir/thirdwindow.ui \
		/opt/qt57/bin/uic
	/opt/qt57/bin/uic guivigir/thirdwindow.ui -o ui_thirdwindow.h

ui_fourth.h: guivigir/fourth.ui \
		/opt/qt57/bin/uic
	/opt/qt57/bin/uic guivigir/fourth.ui -o ui_fourth.h

ui_mainwindow.h: guivigir/mainwindow.ui \
		/opt/qt57/bin/uic
	/opt/qt57/bin/uic guivigir/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: guivigir/main.cpp guivigir/rosgui.h \
		/opt/qt57/include/QtWidgets/QMainWindow \
		/opt/qt57/include/QtWidgets/qmainwindow.h \
		/opt/qt57/include/QtWidgets/qwidget.h \
		/opt/qt57/include/QtGui/qwindowdefs.h \
		/opt/qt57/include/QtCore/qglobal.h \
		/opt/qt57/include/QtCore/qconfig.h \
		/opt/qt57/include/QtCore/qfeatures.h \
		/opt/qt57/include/QtCore/qsystemdetection.h \
		/opt/qt57/include/QtCore/qprocessordetection.h \
		/opt/qt57/include/QtCore/qcompilerdetection.h \
		/opt/qt57/include/QtCore/qtypeinfo.h \
		/opt/qt57/include/QtCore/qtypetraits.h \
		/opt/qt57/include/QtCore/qisenum.h \
		/opt/qt57/include/QtCore/qsysinfo.h \
		/opt/qt57/include/QtCore/qlogging.h \
		/opt/qt57/include/QtCore/qflags.h \
		/opt/qt57/include/QtCore/qatomic.h \
		/opt/qt57/include/QtCore/qbasicatomic.h \
		/opt/qt57/include/QtCore/qatomic_bootstrap.h \
		/opt/qt57/include/QtCore/qgenericatomic.h \
		/opt/qt57/include/QtCore/qatomic_cxx11.h \
		/opt/qt57/include/QtCore/qatomic_msvc.h \
		/opt/qt57/include/QtCore/qglobalstatic.h \
		/opt/qt57/include/QtCore/qmutex.h \
		/opt/qt57/include/QtCore/qnumeric.h \
		/opt/qt57/include/QtCore/qversiontagging.h \
		/opt/qt57/include/QtCore/qobjectdefs.h \
		/opt/qt57/include/QtCore/qnamespace.h \
		/opt/qt57/include/QtCore/qobjectdefs_impl.h \
		/opt/qt57/include/QtGui/qwindowdefs_win.h \
		/opt/qt57/include/QtCore/qobject.h \
		/opt/qt57/include/QtCore/qstring.h \
		/opt/qt57/include/QtCore/qchar.h \
		/opt/qt57/include/QtCore/qbytearray.h \
		/opt/qt57/include/QtCore/qrefcount.h \
		/opt/qt57/include/QtCore/qarraydata.h \
		/opt/qt57/include/QtCore/qstringbuilder.h \
		/opt/qt57/include/QtCore/qlist.h \
		/opt/qt57/include/QtCore/qalgorithms.h \
		/opt/qt57/include/QtCore/qiterator.h \
		/opt/qt57/include/QtCore/qhashfunctions.h \
		/opt/qt57/include/QtCore/qpair.h \
		/opt/qt57/include/QtCore/qbytearraylist.h \
		/opt/qt57/include/QtCore/qstringlist.h \
		/opt/qt57/include/QtCore/qregexp.h \
		/opt/qt57/include/QtCore/qstringmatcher.h \
		/opt/qt57/include/QtCore/qcoreevent.h \
		/opt/qt57/include/QtCore/qscopedpointer.h \
		/opt/qt57/include/QtCore/qmetatype.h \
		/opt/qt57/include/QtCore/qvarlengtharray.h \
		/opt/qt57/include/QtCore/qcontainerfwd.h \
		/opt/qt57/include/QtCore/qobject_impl.h \
		/opt/qt57/include/QtCore/qmargins.h \
		/opt/qt57/include/QtGui/qpaintdevice.h \
		/opt/qt57/include/QtCore/qrect.h \
		/opt/qt57/include/QtCore/qsize.h \
		/opt/qt57/include/QtCore/qpoint.h \
		/opt/qt57/include/QtGui/qpalette.h \
		/opt/qt57/include/QtGui/qcolor.h \
		/opt/qt57/include/QtGui/qrgb.h \
		/opt/qt57/include/QtGui/qrgba64.h \
		/opt/qt57/include/QtGui/qbrush.h \
		/opt/qt57/include/QtCore/qvector.h \
		/opt/qt57/include/QtGui/qmatrix.h \
		/opt/qt57/include/QtGui/qpolygon.h \
		/opt/qt57/include/QtGui/qregion.h \
		/opt/qt57/include/QtCore/qdatastream.h \
		/opt/qt57/include/QtCore/qiodevice.h \
		/opt/qt57/include/QtCore/qline.h \
		/opt/qt57/include/QtGui/qtransform.h \
		/opt/qt57/include/QtGui/qpainterpath.h \
		/opt/qt57/include/QtGui/qimage.h \
		/opt/qt57/include/QtGui/qpixelformat.h \
		/opt/qt57/include/QtGui/qpixmap.h \
		/opt/qt57/include/QtCore/qsharedpointer.h \
		/opt/qt57/include/QtCore/qshareddata.h \
		/opt/qt57/include/QtCore/qhash.h \
		/opt/qt57/include/QtCore/qsharedpointer_impl.h \
		/opt/qt57/include/QtGui/qfont.h \
		/opt/qt57/include/QtGui/qfontmetrics.h \
		/opt/qt57/include/QtGui/qfontinfo.h \
		/opt/qt57/include/QtWidgets/qsizepolicy.h \
		/opt/qt57/include/QtGui/qcursor.h \
		/opt/qt57/include/QtGui/qkeysequence.h \
		/opt/qt57/include/QtGui/qevent.h \
		/opt/qt57/include/QtCore/qvariant.h \
		/opt/qt57/include/QtCore/qmap.h \
		/opt/qt57/include/QtCore/qdebug.h \
		/opt/qt57/include/QtCore/qtextstream.h \
		/opt/qt57/include/QtCore/qlocale.h \
		/opt/qt57/include/QtCore/qset.h \
		/opt/qt57/include/QtCore/qcontiguouscache.h \
		/opt/qt57/include/QtCore/qurl.h \
		/opt/qt57/include/QtCore/qurlquery.h \
		/opt/qt57/include/QtCore/qfile.h \
		/opt/qt57/include/QtCore/qfiledevice.h \
		/opt/qt57/include/QtGui/qvector2d.h \
		/opt/qt57/include/QtGui/qtouchdevice.h \
		/opt/qt57/include/QtWidgets/qtabwidget.h \
		/opt/qt57/include/QtGui/qicon.h \
		guivigir/secondwindow.h \
		guivigir/thirdwindow.h \
		guivigir/fourth.h \
		/opt/qt57/include/QtWidgets/QApplication \
		/opt/qt57/include/QtWidgets/qapplication.h \
		/opt/qt57/include/QtCore/qcoreapplication.h \
		/opt/qt57/include/QtCore/qeventloop.h \
		/opt/qt57/include/QtWidgets/qdesktopwidget.h \
		/opt/qt57/include/QtGui/qguiapplication.h \
		/opt/qt57/include/QtGui/qinputmethod.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o guivigir/main.cpp

rosgui.o: guivigir/rosgui.cpp /opt/qt57/include/QtWidgets/QDesktopWidget \
		/opt/qt57/include/QtWidgets/qdesktopwidget.h \
		/opt/qt57/include/QtWidgets/qwidget.h \
		/opt/qt57/include/QtGui/qwindowdefs.h \
		/opt/qt57/include/QtCore/qglobal.h \
		/opt/qt57/include/QtCore/qconfig.h \
		/opt/qt57/include/QtCore/qfeatures.h \
		/opt/qt57/include/QtCore/qsystemdetection.h \
		/opt/qt57/include/QtCore/qprocessordetection.h \
		/opt/qt57/include/QtCore/qcompilerdetection.h \
		/opt/qt57/include/QtCore/qtypeinfo.h \
		/opt/qt57/include/QtCore/qtypetraits.h \
		/opt/qt57/include/QtCore/qisenum.h \
		/opt/qt57/include/QtCore/qsysinfo.h \
		/opt/qt57/include/QtCore/qlogging.h \
		/opt/qt57/include/QtCore/qflags.h \
		/opt/qt57/include/QtCore/qatomic.h \
		/opt/qt57/include/QtCore/qbasicatomic.h \
		/opt/qt57/include/QtCore/qatomic_bootstrap.h \
		/opt/qt57/include/QtCore/qgenericatomic.h \
		/opt/qt57/include/QtCore/qatomic_cxx11.h \
		/opt/qt57/include/QtCore/qatomic_msvc.h \
		/opt/qt57/include/QtCore/qglobalstatic.h \
		/opt/qt57/include/QtCore/qmutex.h \
		/opt/qt57/include/QtCore/qnumeric.h \
		/opt/qt57/include/QtCore/qversiontagging.h \
		/opt/qt57/include/QtCore/qobjectdefs.h \
		/opt/qt57/include/QtCore/qnamespace.h \
		/opt/qt57/include/QtCore/qobjectdefs_impl.h \
		/opt/qt57/include/QtGui/qwindowdefs_win.h \
		/opt/qt57/include/QtCore/qobject.h \
		/opt/qt57/include/QtCore/qstring.h \
		/opt/qt57/include/QtCore/qchar.h \
		/opt/qt57/include/QtCore/qbytearray.h \
		/opt/qt57/include/QtCore/qrefcount.h \
		/opt/qt57/include/QtCore/qarraydata.h \
		/opt/qt57/include/QtCore/qstringbuilder.h \
		/opt/qt57/include/QtCore/qlist.h \
		/opt/qt57/include/QtCore/qalgorithms.h \
		/opt/qt57/include/QtCore/qiterator.h \
		/opt/qt57/include/QtCore/qhashfunctions.h \
		/opt/qt57/include/QtCore/qpair.h \
		/opt/qt57/include/QtCore/qbytearraylist.h \
		/opt/qt57/include/QtCore/qstringlist.h \
		/opt/qt57/include/QtCore/qregexp.h \
		/opt/qt57/include/QtCore/qstringmatcher.h \
		/opt/qt57/include/QtCore/qcoreevent.h \
		/opt/qt57/include/QtCore/qscopedpointer.h \
		/opt/qt57/include/QtCore/qmetatype.h \
		/opt/qt57/include/QtCore/qvarlengtharray.h \
		/opt/qt57/include/QtCore/qcontainerfwd.h \
		/opt/qt57/include/QtCore/qobject_impl.h \
		/opt/qt57/include/QtCore/qmargins.h \
		/opt/qt57/include/QtGui/qpaintdevice.h \
		/opt/qt57/include/QtCore/qrect.h \
		/opt/qt57/include/QtCore/qsize.h \
		/opt/qt57/include/QtCore/qpoint.h \
		/opt/qt57/include/QtGui/qpalette.h \
		/opt/qt57/include/QtGui/qcolor.h \
		/opt/qt57/include/QtGui/qrgb.h \
		/opt/qt57/include/QtGui/qrgba64.h \
		/opt/qt57/include/QtGui/qbrush.h \
		/opt/qt57/include/QtCore/qvector.h \
		/opt/qt57/include/QtGui/qmatrix.h \
		/opt/qt57/include/QtGui/qpolygon.h \
		/opt/qt57/include/QtGui/qregion.h \
		/opt/qt57/include/QtCore/qdatastream.h \
		/opt/qt57/include/QtCore/qiodevice.h \
		/opt/qt57/include/QtCore/qline.h \
		/opt/qt57/include/QtGui/qtransform.h \
		/opt/qt57/include/QtGui/qpainterpath.h \
		/opt/qt57/include/QtGui/qimage.h \
		/opt/qt57/include/QtGui/qpixelformat.h \
		/opt/qt57/include/QtGui/qpixmap.h \
		/opt/qt57/include/QtCore/qsharedpointer.h \
		/opt/qt57/include/QtCore/qshareddata.h \
		/opt/qt57/include/QtCore/qhash.h \
		/opt/qt57/include/QtCore/qsharedpointer_impl.h \
		/opt/qt57/include/QtGui/qfont.h \
		/opt/qt57/include/QtGui/qfontmetrics.h \
		/opt/qt57/include/QtGui/qfontinfo.h \
		/opt/qt57/include/QtWidgets/qsizepolicy.h \
		/opt/qt57/include/QtGui/qcursor.h \
		/opt/qt57/include/QtGui/qkeysequence.h \
		/opt/qt57/include/QtGui/qevent.h \
		/opt/qt57/include/QtCore/qvariant.h \
		/opt/qt57/include/QtCore/qmap.h \
		/opt/qt57/include/QtCore/qdebug.h \
		/opt/qt57/include/QtCore/qtextstream.h \
		/opt/qt57/include/QtCore/qlocale.h \
		/opt/qt57/include/QtCore/qset.h \
		/opt/qt57/include/QtCore/qcontiguouscache.h \
		/opt/qt57/include/QtCore/qurl.h \
		/opt/qt57/include/QtCore/qurlquery.h \
		/opt/qt57/include/QtCore/qfile.h \
		/opt/qt57/include/QtCore/qfiledevice.h \
		/opt/qt57/include/QtGui/qvector2d.h \
		/opt/qt57/include/QtGui/qtouchdevice.h \
		guivigir/rosgui.h \
		/opt/qt57/include/QtWidgets/QMainWindow \
		/opt/qt57/include/QtWidgets/qmainwindow.h \
		/opt/qt57/include/QtWidgets/qtabwidget.h \
		/opt/qt57/include/QtGui/qicon.h \
		guivigir/secondwindow.h \
		guivigir/thirdwindow.h \
		guivigir/fourth.h \
		ui_rosgui.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rosgui.o guivigir/rosgui.cpp

secondwindow.o: guivigir/secondwindow.cpp guivigir/secondwindow.h \
		/opt/qt57/include/QtWidgets/QMainWindow \
		/opt/qt57/include/QtWidgets/qmainwindow.h \
		/opt/qt57/include/QtWidgets/qwidget.h \
		/opt/qt57/include/QtGui/qwindowdefs.h \
		/opt/qt57/include/QtCore/qglobal.h \
		/opt/qt57/include/QtCore/qconfig.h \
		/opt/qt57/include/QtCore/qfeatures.h \
		/opt/qt57/include/QtCore/qsystemdetection.h \
		/opt/qt57/include/QtCore/qprocessordetection.h \
		/opt/qt57/include/QtCore/qcompilerdetection.h \
		/opt/qt57/include/QtCore/qtypeinfo.h \
		/opt/qt57/include/QtCore/qtypetraits.h \
		/opt/qt57/include/QtCore/qisenum.h \
		/opt/qt57/include/QtCore/qsysinfo.h \
		/opt/qt57/include/QtCore/qlogging.h \
		/opt/qt57/include/QtCore/qflags.h \
		/opt/qt57/include/QtCore/qatomic.h \
		/opt/qt57/include/QtCore/qbasicatomic.h \
		/opt/qt57/include/QtCore/qatomic_bootstrap.h \
		/opt/qt57/include/QtCore/qgenericatomic.h \
		/opt/qt57/include/QtCore/qatomic_cxx11.h \
		/opt/qt57/include/QtCore/qatomic_msvc.h \
		/opt/qt57/include/QtCore/qglobalstatic.h \
		/opt/qt57/include/QtCore/qmutex.h \
		/opt/qt57/include/QtCore/qnumeric.h \
		/opt/qt57/include/QtCore/qversiontagging.h \
		/opt/qt57/include/QtCore/qobjectdefs.h \
		/opt/qt57/include/QtCore/qnamespace.h \
		/opt/qt57/include/QtCore/qobjectdefs_impl.h \
		/opt/qt57/include/QtGui/qwindowdefs_win.h \
		/opt/qt57/include/QtCore/qobject.h \
		/opt/qt57/include/QtCore/qstring.h \
		/opt/qt57/include/QtCore/qchar.h \
		/opt/qt57/include/QtCore/qbytearray.h \
		/opt/qt57/include/QtCore/qrefcount.h \
		/opt/qt57/include/QtCore/qarraydata.h \
		/opt/qt57/include/QtCore/qstringbuilder.h \
		/opt/qt57/include/QtCore/qlist.h \
		/opt/qt57/include/QtCore/qalgorithms.h \
		/opt/qt57/include/QtCore/qiterator.h \
		/opt/qt57/include/QtCore/qhashfunctions.h \
		/opt/qt57/include/QtCore/qpair.h \
		/opt/qt57/include/QtCore/qbytearraylist.h \
		/opt/qt57/include/QtCore/qstringlist.h \
		/opt/qt57/include/QtCore/qregexp.h \
		/opt/qt57/include/QtCore/qstringmatcher.h \
		/opt/qt57/include/QtCore/qcoreevent.h \
		/opt/qt57/include/QtCore/qscopedpointer.h \
		/opt/qt57/include/QtCore/qmetatype.h \
		/opt/qt57/include/QtCore/qvarlengtharray.h \
		/opt/qt57/include/QtCore/qcontainerfwd.h \
		/opt/qt57/include/QtCore/qobject_impl.h \
		/opt/qt57/include/QtCore/qmargins.h \
		/opt/qt57/include/QtGui/qpaintdevice.h \
		/opt/qt57/include/QtCore/qrect.h \
		/opt/qt57/include/QtCore/qsize.h \
		/opt/qt57/include/QtCore/qpoint.h \
		/opt/qt57/include/QtGui/qpalette.h \
		/opt/qt57/include/QtGui/qcolor.h \
		/opt/qt57/include/QtGui/qrgb.h \
		/opt/qt57/include/QtGui/qrgba64.h \
		/opt/qt57/include/QtGui/qbrush.h \
		/opt/qt57/include/QtCore/qvector.h \
		/opt/qt57/include/QtGui/qmatrix.h \
		/opt/qt57/include/QtGui/qpolygon.h \
		/opt/qt57/include/QtGui/qregion.h \
		/opt/qt57/include/QtCore/qdatastream.h \
		/opt/qt57/include/QtCore/qiodevice.h \
		/opt/qt57/include/QtCore/qline.h \
		/opt/qt57/include/QtGui/qtransform.h \
		/opt/qt57/include/QtGui/qpainterpath.h \
		/opt/qt57/include/QtGui/qimage.h \
		/opt/qt57/include/QtGui/qpixelformat.h \
		/opt/qt57/include/QtGui/qpixmap.h \
		/opt/qt57/include/QtCore/qsharedpointer.h \
		/opt/qt57/include/QtCore/qshareddata.h \
		/opt/qt57/include/QtCore/qhash.h \
		/opt/qt57/include/QtCore/qsharedpointer_impl.h \
		/opt/qt57/include/QtGui/qfont.h \
		/opt/qt57/include/QtGui/qfontmetrics.h \
		/opt/qt57/include/QtGui/qfontinfo.h \
		/opt/qt57/include/QtWidgets/qsizepolicy.h \
		/opt/qt57/include/QtGui/qcursor.h \
		/opt/qt57/include/QtGui/qkeysequence.h \
		/opt/qt57/include/QtGui/qevent.h \
		/opt/qt57/include/QtCore/qvariant.h \
		/opt/qt57/include/QtCore/qmap.h \
		/opt/qt57/include/QtCore/qdebug.h \
		/opt/qt57/include/QtCore/qtextstream.h \
		/opt/qt57/include/QtCore/qlocale.h \
		/opt/qt57/include/QtCore/qset.h \
		/opt/qt57/include/QtCore/qcontiguouscache.h \
		/opt/qt57/include/QtCore/qurl.h \
		/opt/qt57/include/QtCore/qurlquery.h \
		/opt/qt57/include/QtCore/qfile.h \
		/opt/qt57/include/QtCore/qfiledevice.h \
		/opt/qt57/include/QtGui/qvector2d.h \
		/opt/qt57/include/QtGui/qtouchdevice.h \
		/opt/qt57/include/QtWidgets/qtabwidget.h \
		/opt/qt57/include/QtGui/qicon.h \
		guivigir/rosgui.h \
		guivigir/thirdwindow.h \
		guivigir/fourth.h \
		ui_secondwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o secondwindow.o guivigir/secondwindow.cpp

thirdwindow.o: guivigir/thirdwindow.cpp guivigir/thirdwindow.h \
		/opt/qt57/include/QtWidgets/QMainWindow \
		/opt/qt57/include/QtWidgets/qmainwindow.h \
		/opt/qt57/include/QtWidgets/qwidget.h \
		/opt/qt57/include/QtGui/qwindowdefs.h \
		/opt/qt57/include/QtCore/qglobal.h \
		/opt/qt57/include/QtCore/qconfig.h \
		/opt/qt57/include/QtCore/qfeatures.h \
		/opt/qt57/include/QtCore/qsystemdetection.h \
		/opt/qt57/include/QtCore/qprocessordetection.h \
		/opt/qt57/include/QtCore/qcompilerdetection.h \
		/opt/qt57/include/QtCore/qtypeinfo.h \
		/opt/qt57/include/QtCore/qtypetraits.h \
		/opt/qt57/include/QtCore/qisenum.h \
		/opt/qt57/include/QtCore/qsysinfo.h \
		/opt/qt57/include/QtCore/qlogging.h \
		/opt/qt57/include/QtCore/qflags.h \
		/opt/qt57/include/QtCore/qatomic.h \
		/opt/qt57/include/QtCore/qbasicatomic.h \
		/opt/qt57/include/QtCore/qatomic_bootstrap.h \
		/opt/qt57/include/QtCore/qgenericatomic.h \
		/opt/qt57/include/QtCore/qatomic_cxx11.h \
		/opt/qt57/include/QtCore/qatomic_msvc.h \
		/opt/qt57/include/QtCore/qglobalstatic.h \
		/opt/qt57/include/QtCore/qmutex.h \
		/opt/qt57/include/QtCore/qnumeric.h \
		/opt/qt57/include/QtCore/qversiontagging.h \
		/opt/qt57/include/QtCore/qobjectdefs.h \
		/opt/qt57/include/QtCore/qnamespace.h \
		/opt/qt57/include/QtCore/qobjectdefs_impl.h \
		/opt/qt57/include/QtGui/qwindowdefs_win.h \
		/opt/qt57/include/QtCore/qobject.h \
		/opt/qt57/include/QtCore/qstring.h \
		/opt/qt57/include/QtCore/qchar.h \
		/opt/qt57/include/QtCore/qbytearray.h \
		/opt/qt57/include/QtCore/qrefcount.h \
		/opt/qt57/include/QtCore/qarraydata.h \
		/opt/qt57/include/QtCore/qstringbuilder.h \
		/opt/qt57/include/QtCore/qlist.h \
		/opt/qt57/include/QtCore/qalgorithms.h \
		/opt/qt57/include/QtCore/qiterator.h \
		/opt/qt57/include/QtCore/qhashfunctions.h \
		/opt/qt57/include/QtCore/qpair.h \
		/opt/qt57/include/QtCore/qbytearraylist.h \
		/opt/qt57/include/QtCore/qstringlist.h \
		/opt/qt57/include/QtCore/qregexp.h \
		/opt/qt57/include/QtCore/qstringmatcher.h \
		/opt/qt57/include/QtCore/qcoreevent.h \
		/opt/qt57/include/QtCore/qscopedpointer.h \
		/opt/qt57/include/QtCore/qmetatype.h \
		/opt/qt57/include/QtCore/qvarlengtharray.h \
		/opt/qt57/include/QtCore/qcontainerfwd.h \
		/opt/qt57/include/QtCore/qobject_impl.h \
		/opt/qt57/include/QtCore/qmargins.h \
		/opt/qt57/include/QtGui/qpaintdevice.h \
		/opt/qt57/include/QtCore/qrect.h \
		/opt/qt57/include/QtCore/qsize.h \
		/opt/qt57/include/QtCore/qpoint.h \
		/opt/qt57/include/QtGui/qpalette.h \
		/opt/qt57/include/QtGui/qcolor.h \
		/opt/qt57/include/QtGui/qrgb.h \
		/opt/qt57/include/QtGui/qrgba64.h \
		/opt/qt57/include/QtGui/qbrush.h \
		/opt/qt57/include/QtCore/qvector.h \
		/opt/qt57/include/QtGui/qmatrix.h \
		/opt/qt57/include/QtGui/qpolygon.h \
		/opt/qt57/include/QtGui/qregion.h \
		/opt/qt57/include/QtCore/qdatastream.h \
		/opt/qt57/include/QtCore/qiodevice.h \
		/opt/qt57/include/QtCore/qline.h \
		/opt/qt57/include/QtGui/qtransform.h \
		/opt/qt57/include/QtGui/qpainterpath.h \
		/opt/qt57/include/QtGui/qimage.h \
		/opt/qt57/include/QtGui/qpixelformat.h \
		/opt/qt57/include/QtGui/qpixmap.h \
		/opt/qt57/include/QtCore/qsharedpointer.h \
		/opt/qt57/include/QtCore/qshareddata.h \
		/opt/qt57/include/QtCore/qhash.h \
		/opt/qt57/include/QtCore/qsharedpointer_impl.h \
		/opt/qt57/include/QtGui/qfont.h \
		/opt/qt57/include/QtGui/qfontmetrics.h \
		/opt/qt57/include/QtGui/qfontinfo.h \
		/opt/qt57/include/QtWidgets/qsizepolicy.h \
		/opt/qt57/include/QtGui/qcursor.h \
		/opt/qt57/include/QtGui/qkeysequence.h \
		/opt/qt57/include/QtGui/qevent.h \
		/opt/qt57/include/QtCore/qvariant.h \
		/opt/qt57/include/QtCore/qmap.h \
		/opt/qt57/include/QtCore/qdebug.h \
		/opt/qt57/include/QtCore/qtextstream.h \
		/opt/qt57/include/QtCore/qlocale.h \
		/opt/qt57/include/QtCore/qset.h \
		/opt/qt57/include/QtCore/qcontiguouscache.h \
		/opt/qt57/include/QtCore/qurl.h \
		/opt/qt57/include/QtCore/qurlquery.h \
		/opt/qt57/include/QtCore/qfile.h \
		/opt/qt57/include/QtCore/qfiledevice.h \
		/opt/qt57/include/QtGui/qvector2d.h \
		/opt/qt57/include/QtGui/qtouchdevice.h \
		/opt/qt57/include/QtWidgets/qtabwidget.h \
		/opt/qt57/include/QtGui/qicon.h \
		ui_thirdwindow.h \
		guivigir/rosgui.h \
		guivigir/secondwindow.h \
		guivigir/fourth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thirdwindow.o guivigir/thirdwindow.cpp

fourth.o: guivigir/fourth.cpp guivigir/fourth.h \
		/opt/qt57/include/QtWidgets/QMainWindow \
		/opt/qt57/include/QtWidgets/qmainwindow.h \
		/opt/qt57/include/QtWidgets/qwidget.h \
		/opt/qt57/include/QtGui/qwindowdefs.h \
		/opt/qt57/include/QtCore/qglobal.h \
		/opt/qt57/include/QtCore/qconfig.h \
		/opt/qt57/include/QtCore/qfeatures.h \
		/opt/qt57/include/QtCore/qsystemdetection.h \
		/opt/qt57/include/QtCore/qprocessordetection.h \
		/opt/qt57/include/QtCore/qcompilerdetection.h \
		/opt/qt57/include/QtCore/qtypeinfo.h \
		/opt/qt57/include/QtCore/qtypetraits.h \
		/opt/qt57/include/QtCore/qisenum.h \
		/opt/qt57/include/QtCore/qsysinfo.h \
		/opt/qt57/include/QtCore/qlogging.h \
		/opt/qt57/include/QtCore/qflags.h \
		/opt/qt57/include/QtCore/qatomic.h \
		/opt/qt57/include/QtCore/qbasicatomic.h \
		/opt/qt57/include/QtCore/qatomic_bootstrap.h \
		/opt/qt57/include/QtCore/qgenericatomic.h \
		/opt/qt57/include/QtCore/qatomic_cxx11.h \
		/opt/qt57/include/QtCore/qatomic_msvc.h \
		/opt/qt57/include/QtCore/qglobalstatic.h \
		/opt/qt57/include/QtCore/qmutex.h \
		/opt/qt57/include/QtCore/qnumeric.h \
		/opt/qt57/include/QtCore/qversiontagging.h \
		/opt/qt57/include/QtCore/qobjectdefs.h \
		/opt/qt57/include/QtCore/qnamespace.h \
		/opt/qt57/include/QtCore/qobjectdefs_impl.h \
		/opt/qt57/include/QtGui/qwindowdefs_win.h \
		/opt/qt57/include/QtCore/qobject.h \
		/opt/qt57/include/QtCore/qstring.h \
		/opt/qt57/include/QtCore/qchar.h \
		/opt/qt57/include/QtCore/qbytearray.h \
		/opt/qt57/include/QtCore/qrefcount.h \
		/opt/qt57/include/QtCore/qarraydata.h \
		/opt/qt57/include/QtCore/qstringbuilder.h \
		/opt/qt57/include/QtCore/qlist.h \
		/opt/qt57/include/QtCore/qalgorithms.h \
		/opt/qt57/include/QtCore/qiterator.h \
		/opt/qt57/include/QtCore/qhashfunctions.h \
		/opt/qt57/include/QtCore/qpair.h \
		/opt/qt57/include/QtCore/qbytearraylist.h \
		/opt/qt57/include/QtCore/qstringlist.h \
		/opt/qt57/include/QtCore/qregexp.h \
		/opt/qt57/include/QtCore/qstringmatcher.h \
		/opt/qt57/include/QtCore/qcoreevent.h \
		/opt/qt57/include/QtCore/qscopedpointer.h \
		/opt/qt57/include/QtCore/qmetatype.h \
		/opt/qt57/include/QtCore/qvarlengtharray.h \
		/opt/qt57/include/QtCore/qcontainerfwd.h \
		/opt/qt57/include/QtCore/qobject_impl.h \
		/opt/qt57/include/QtCore/qmargins.h \
		/opt/qt57/include/QtGui/qpaintdevice.h \
		/opt/qt57/include/QtCore/qrect.h \
		/opt/qt57/include/QtCore/qsize.h \
		/opt/qt57/include/QtCore/qpoint.h \
		/opt/qt57/include/QtGui/qpalette.h \
		/opt/qt57/include/QtGui/qcolor.h \
		/opt/qt57/include/QtGui/qrgb.h \
		/opt/qt57/include/QtGui/qrgba64.h \
		/opt/qt57/include/QtGui/qbrush.h \
		/opt/qt57/include/QtCore/qvector.h \
		/opt/qt57/include/QtGui/qmatrix.h \
		/opt/qt57/include/QtGui/qpolygon.h \
		/opt/qt57/include/QtGui/qregion.h \
		/opt/qt57/include/QtCore/qdatastream.h \
		/opt/qt57/include/QtCore/qiodevice.h \
		/opt/qt57/include/QtCore/qline.h \
		/opt/qt57/include/QtGui/qtransform.h \
		/opt/qt57/include/QtGui/qpainterpath.h \
		/opt/qt57/include/QtGui/qimage.h \
		/opt/qt57/include/QtGui/qpixelformat.h \
		/opt/qt57/include/QtGui/qpixmap.h \
		/opt/qt57/include/QtCore/qsharedpointer.h \
		/opt/qt57/include/QtCore/qshareddata.h \
		/opt/qt57/include/QtCore/qhash.h \
		/opt/qt57/include/QtCore/qsharedpointer_impl.h \
		/opt/qt57/include/QtGui/qfont.h \
		/opt/qt57/include/QtGui/qfontmetrics.h \
		/opt/qt57/include/QtGui/qfontinfo.h \
		/opt/qt57/include/QtWidgets/qsizepolicy.h \
		/opt/qt57/include/QtGui/qcursor.h \
		/opt/qt57/include/QtGui/qkeysequence.h \
		/opt/qt57/include/QtGui/qevent.h \
		/opt/qt57/include/QtCore/qvariant.h \
		/opt/qt57/include/QtCore/qmap.h \
		/opt/qt57/include/QtCore/qdebug.h \
		/opt/qt57/include/QtCore/qtextstream.h \
		/opt/qt57/include/QtCore/qlocale.h \
		/opt/qt57/include/QtCore/qset.h \
		/opt/qt57/include/QtCore/qcontiguouscache.h \
		/opt/qt57/include/QtCore/qurl.h \
		/opt/qt57/include/QtCore/qurlquery.h \
		/opt/qt57/include/QtCore/qfile.h \
		/opt/qt57/include/QtCore/qfiledevice.h \
		/opt/qt57/include/QtGui/qvector2d.h \
		/opt/qt57/include/QtGui/qtouchdevice.h \
		/opt/qt57/include/QtWidgets/qtabwidget.h \
		/opt/qt57/include/QtGui/qicon.h \
		ui_fourth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fourth.o guivigir/fourth.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_rosgui.o: moc_rosgui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rosgui.o moc_rosgui.cpp

moc_secondwindow.o: moc_secondwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_secondwindow.o moc_secondwindow.cpp

moc_thirdwindow.o: moc_thirdwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_thirdwindow.o moc_thirdwindow.cpp

moc_fourth.o: moc_fourth.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fourth.o moc_fourth.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

